- name: Check if user exists
  shell: id -u {{ user_name }}
  register: user_id
  ignore_errors: yes

- name: Create user if it does not exist
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/bash
  when: user_id.rc != 0