- name: Upgrade packages with apt
  when: ansible_pkg_mgr == 'apt'
  ansible.builtin.apt:
    upgrade: dist

- name: Upgrade packages with yum
  when: ansible_pkg_mgr == 'yum'
  ansible.builtin.yum:
    name: "*"
    state: latest # noqa: package-latest
    exclude: kernel*